default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: root
  host: localhost
  pool: 5

development:
  <<: *default
  database: Artemisa_development

test:
  <<: *default
  database: Artemisa_test

production:
  <<: *default
  database: d2tt75507ec5l6
  username: rbocsqpjqcabya
  password: ev4DKxUpwETqOmcrD9oxtVFHbn
