default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host: localhost
  pool: 5

development:
  <<: *default
  database: Artemisa_development

test:
  <<: *default
  database: Artemisa_test

production:
  <<: *default
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
